In [1]:
# Dinh Hoang Viet Phuong - 301123263

In [2]:
# import all libaries
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

In [3]:
# 1. Load the banknote_authentication.csv file and store it in a data frame 

file_path = "X:\\mid-term\\banknote_authentication.csv"

# Extract input matrix X and output column y from the data frame
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

print(X)
print(y)

[[  4.5459    8.1674   -2.4586   -1.4621 ]
 [  3.866    -2.6383    1.9242    0.10645]
 [  3.4566    9.5228   -4.0112   -3.5944 ]
 ...
 [ -3.7503  -13.4586   17.5932   -2.7771 ]
 [ -3.5637   -8.3827   12.393    -1.2823 ]
 [ -2.5419   -0.65804   2.6842    1.1952 ]]
[0 0 0 ... 1 1 1]


In [4]:
# Split the dataset into train and test datasets using train_test_split method. Let N = length of testset

# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
# Getting the length of the test dataset
N = len(X_test)

print(f"Number of samples in test set (N): {N}")

Number of samples in test set (N): 275


In [5]:
# Initialize the weights and call backprop function to compute the final weights W1, W2.

# Activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

In [6]:
# Initialize weights and biases
input_size = 4
hidden_size = 5
output_size = 1

np.random.seed(42)
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

In [7]:
# Forward propagation
def forward_propagation(X):
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)
    return a1, a2

# Backpropagation
def backprop(X, y, a1, a2, learning_rate=0.01):
    global W1, W2, b1, b2

    m = X.shape[0]
    
    # Compute the error
    dz2 = a2 - y
    dw2 = 1/m * np.dot(a1.T, dz2)
    db2 = 1/m * np.sum(dz2, axis=0, keepdims=True)
    
    dz1 = np.dot(dz2, W2.T) * sigmoid_derivative(a1)
    dw1 = 1/m * np.dot(X.T, dz1)
    db1 = 1/m * np.sum(dz1, axis=0, keepdims=True)
    
    # Update weights and biases
    W1 -= learning_rate * dw1
    W2 -= learning_rate * dw2
    b1 -= learning_rate * db1
    b2 -= learning_rate * db2

In [8]:
# Training the neural network
y_train = y_train.reshape(-1,1)
epochs = 10000
learning_rate = 0.01

for epoch in range(epochs):
    a1, a2 = forward_propagation(X_train)
    backprop(X_train, y_train, a1, a2, learning_rate)

print("Final Weights (W1):")
print(W1)
print("\nFinal Weights (W2):")
print(W2)

Final Weights (W1):
[[-1.48745915 -0.10444098  1.23500188  2.22432035 -0.21161354]
 [-0.92250886  1.59114695  0.75822483  0.16204109  0.55278138]
 [-1.11259572 -0.41610625  0.89263155 -0.60675066 -1.7336051 ]
 [-0.16511489 -1.01442938  0.23806351 -1.1582326  -1.40317239]]

Final Weights (W2):
[[ 4.64768819]
 [-0.00931389]
 [-2.9047126 ]
 [-1.480751  ]
 [ 0.45095132]]


In [9]:
# Get predictions on test set
_, predictions = forward_propagation(X_test)

# Print results
print(f"N = ", N)
for i in range(N):
    print(f"x= {X_test[i]} ,y= {y_test[i]} , predicted value= {predictions[i][0]}")

N =  275
x= [-3.1128 -6.841  10.7402 -1.0172] ,y= 1 , predicted value= 0.8816409616597232
x= [ 3.7818  -2.8846   2.2558  -0.15734] ,y= 0 , predicted value= 0.01579387924337087
x= [3.9433 2.5017 1.5215 0.903 ] ,y= 0 , predicted value= 0.013624044162917624
x= [ 0.5195 -3.2633  3.0895 -0.9849] ,y= 0 , predicted value= 0.6859399471316888
x= [ 0.3223  -0.89808  8.0883   0.69222] ,y= 0 , predicted value= 0.0566169856042852
x= [ 1.2746  8.8172 -1.5323 -1.7957] ,y= 0 , predicted value= 0.02117792140185125
x= [ 0.5195 -3.2633  3.0895 -0.9849] ,y= 0 , predicted value= 0.6859399471316888
x= [ 2.3678  -6.839    8.4207  -0.44829] ,y= 0 , predicted value= 0.03314385180125299
x= [-0.8734   -0.033118 -0.20165   0.55774 ] ,y= 1 , predicted value= 0.9853364512754603
x= [ 4.2475   1.4816  -0.48355  0.95343] ,y= 0 , predicted value= 0.016133976071048106
x= [-3.7747   2.5162   0.83341 -0.30993] ,y= 1 , predicted value= 0.9920723454975366
x= [-2.7143 11.4535  2.1092 -3.9629] ,y= 0 , predicted value= 0.05575